language: java
dist: trusty
jdk:
  - oraclejdk8  
  - openjdk10
  - oraclejdk11
script: "mvn clean package"
branches:
  except:
    - travis
notifications:
  email: ifitnessworkout@gmail.com
after_success:
  - mvn clean install
